Ch lex.repvec to lex.vector
For preventing the AttributeError: `File "spacy/lexeme.pyx", line 159, in spacy.lexeme.Lexeme.repvec.__get__ (spacy/lexeme.cpp:5016)
AttributeError: lex.repvec has been renamed to lex.vector`